// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrHQTVWPuyzobw1SbYmWwdENITsjesD-E',
    appId: '1:212008922624:web:6302ddace53e3e413df2e5',
    messagingSenderId: '212008922624',
    projectId: 'rifa-funfai-e3985',
    authDomain: 'rifa-funfai-e3985.firebaseapp.com',
    storageBucket: 'rifa-funfai-e3985.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvjOKL5Pr7yUN5lcwJSi_xRKIRsLktHmE',
    appId: '1:212008922624:ios:8a03db03d3d34e113df2e5',
    messagingSenderId: '212008922624',
    projectId: 'rifa-funfai-e3985',
    storageBucket: 'rifa-funfai-e3985.appspot.com',
    iosBundleId: 'com.example.rifa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrHQTVWPuyzobw1SbYmWwdENITsjesD-E',
    appId: '1:212008922624:web:9383c2c646e1294a3df2e5',
    messagingSenderId: '212008922624',
    projectId: 'rifa-funfai-e3985',
    authDomain: 'rifa-funfai-e3985.firebaseapp.com',
    storageBucket: 'rifa-funfai-e3985.appspot.com',
  );

}